# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

1.15.4


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
a = np.empty(10)
print(a)

[2.57153710e+151 5.20457918e+149 4.76304916e-313 3.53860623e-308
 1.33360303e+241 6.76067859e-311 2.34140334e-258 2.85308965e-313
 2.14793507e-308 1.33360297e+241]


#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
# https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-33.php
print(a.size * a.itemsize) # 10 * 8
print(type(a[0]))


80
<class 'numpy.float64'>


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
a = np.empty(10)
a[5] = 1
print(a)

[2.57153710e+151 5.20457918e+149 4.76304916e-313 3.53860623e-308
 1.33360303e+241 1.00000000e+000 2.34140334e-258 2.85308965e-313
 2.14793507e-308 1.33360297e+241]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
a = np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [7]:
b1 = a[::-1]
print(b1)
b2 = np.fliplr([a])[0]
print(b2)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
print(np.arange(0,9).reshape(3,3))


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [9]:
a = np.array([1, 2, 0, 0, 4, 0])
ind = np.where(a != 0)
print(ind)


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [10]:
a = np.identity(3) # square matrix
print(a)
b = np.eye(3,4) # any shape can be used
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [11]:
a = np.random.rand(3, 3, 3)
print(a)

[[[0.25229544 0.5915959  0.58653273]
  [0.85416518 0.65198274 0.10819351]
  [0.25055974 0.6199129  0.35958442]]

 [[0.79245754 0.3419468  0.30700059]
  [0.97707488 0.91818826 0.96059499]
  [0.39942256 0.69755064 0.46025813]]

 [[0.25276357 0.90384834 0.41331064]
  [0.12834991 0.84348503 0.90592168]
  [0.98682076 0.47077312 0.43718151]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [12]:
b = np.random.rand(10, 10)
mini = np.min(b)
maxi = np.max(b)
print(b, mini, maxi)

[[0.00907587 0.47416387 0.96271593 0.84652716 0.86261825 0.72028997
  0.35524705 0.41858225 0.40922564 0.82819196]
 [0.21665123 0.59322369 0.52058637 0.73148045 0.46926825 0.24964741
  0.24683643 0.54989334 0.21994829 0.80961871]
 [0.73683368 0.1525569  0.57778711 0.55175145 0.60786074 0.35269804
  0.04796757 0.04554313 0.35887643 0.6628868 ]
 [0.55258534 0.24395645 0.01878162 0.79939314 0.73460839 0.80772884
  0.97087315 0.60752116 0.96738905 0.46158242]
 [0.38262209 0.94263156 0.61930241 0.41424256 0.10303498 0.48874279
  0.68834243 0.91523973 0.42601574 0.07621602]
 [0.3636251  0.93629262 0.09497495 0.78941481 0.19643083 0.42292704
  0.86630869 0.15364793 0.32984428 0.42002273]
 [0.09287455 0.55817921 0.73844567 0.05296024 0.28519723 0.94786064
  0.86554173 0.84763677 0.29792653 0.26110112]
 [0.6001233  0.30400061 0.73946176 0.61295057 0.84030537 0.96500258
  0.13417176 0.4352417  0.18481488 0.09039924]
 [0.30015928 0.27717312 0.33257232 0.3044914  0.77339508 0.40355011
  0.75381068

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [13]:
a = np.random.rand(30)
b = np.mean(a)
print(a, b)

[0.44013866 0.05290757 0.94564318 0.54260236 0.47095842 0.82580544
 0.15301698 0.56679675 0.48265242 0.06109936 0.09557195 0.22041656
 0.14085281 0.53200243 0.85336533 0.89510141 0.52564331 0.45038962
 0.91678184 0.72064497 0.67285683 0.10472591 0.17455568 0.4270252
 0.20699448 0.46050231 0.34051985 0.35366264 0.81506949 0.17968502] 0.4542662929715445


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [14]:
# o 0 * np.nan = np.nan
# o np.nan == np.nan = false -> False
# o np.inf > np.nan = false -> False
# o np.nan - np.nan = np.nan
# x np.nan in set([np.nan]) = np.nan -> True
# o0.3 == 3 * 0.1 = false -> False
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)



nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [15]:
# numpy array creation routines
# https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.array-creation.html



#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [16]:
# (1, 5, 4)
a = np.arange(0, 6*7*8).reshape(6, 7, 8)
print(a[1][5][4])

100


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [17]:
# normalization
a = np.random.rand(5,5)
b = (a - a.min())/ (np.max(a) - np.min(a))
print(a)
print(b)


[[0.71416364 0.02876355 0.27058966 0.85347181 0.75052046]
 [0.60778635 0.34890514 0.54266421 0.85961693 0.78193834]
 [0.54258548 0.39751746 0.50943389 0.07194324 0.0029053 ]
 [0.28469765 0.97749826 0.34175814 0.41997421 0.22354142]
 [0.15593489 0.08359204 0.4770819  0.28241757 0.21593391]]
[[0.72980041 0.02653236 0.27466273 0.87274026 0.76710503]
 [0.62064993 0.35501985 0.55383009 0.87904557 0.79934195]
 [0.55374931 0.40489946 0.51973347 0.07083771 0.        ]
 [0.2891385  1.         0.34768652 0.42794164 0.22638797]
 [0.15701898 0.08279019 0.48653809 0.28679899 0.21858213]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [18]:
# https://docs.scipy.org/doc/numpy-1.15.0/reference/arrays.dtypes.html
dt = np.dtype((np.uint32, {'R':(np.uint8,0), 'G':(np.uint8,1), 'B':(np.uint8,2), 'A':(np.uint8,3)}))
print(dt)
a = np.empty(5, dtype=dt)
print(a.dtype)

(numpy.uint32, [('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])
(numpy.uint32, [('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [19]:
a = np.random.rand(5,3)
b = np.random.rand(3, 2)
c = a.dot(b)
print(c)

[[0.45953917 0.4285132 ]
 [0.33000136 0.76316398]
 [0.82430334 0.96539801]
 [0.42632673 0.49708731]
 [0.70627673 1.00301072]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [20]:
# print(sum(range(5),-1)) # sum of (0, 1, 2, 3, 4) = 10, -1
# from numpy import *
# print(sum(range(5),-1)) # (0, 1, 2, 3, 4), -1 -> sum(-1, 0, 1, 2, 3)  = 5 -> 10 is correct answer
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1)) # sum(a, axis), axis=-1



9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)